name: 'foss_data_platform'
version: '1.0.0'
config-version: 2

profile: 'foss_data_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  foss_data_platform:
    staging:
      +materialized: table

seeds:
  foss_data_platform:
    +quote_columns: false

vars:
  # Add your variables here
  start_date: "2024-01-01"
  end_date: "2024-12-31"


