name: 'stavanger_parking'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'stavanger_parking'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring data models
models:
  stavanger_parking:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
      core:
        +materialized: table
        +schema: marts_core
      marketing:
        +materialized: table
        +schema: marts_marketing

# Seeds configuration
seeds:
  stavanger_parking:
    +schema: raw_data
    +column_types:
      id: varchar(255)
      timestamp: timestamp
      location: varchar(255)
      occupancy: integer
      capacity: integer

# Documentation
docs-paths: ["docs"]
