name: 'stavanger_parking'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'stavanger_parking'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Ensure required schemas exist (Trino memory connector)
on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS memory.default_raw_data"
  - "CREATE SCHEMA IF NOT EXISTS memory.default_staging"
  - "CREATE SCHEMA IF NOT EXISTS memory.default_intermediate"
  - "CREATE SCHEMA IF NOT EXISTS memory.default_marts"
  - "CREATE SCHEMA IF NOT EXISTS memory.default_marts_core"
  - "CREATE SCHEMA IF NOT EXISTS memory.default_marts_marketing"

# Configuring data models
models:
  stavanger_parking:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +schema: default_staging
    intermediate:
      +materialized: view
      +schema: default_intermediate
    marts:
      +materialized: table
      +schema: default_marts
      core:
        +materialized: table
        +schema: default_marts_core
      marketing:
        +materialized: table
        +schema: default_marts_marketing

# Seeds configuration
seeds:
  stavanger_parking:
    +schema: default_raw_data
    +column_types:
      name: varchar(255)
      available_spaces: integer
      lat: varchar(64)
      lon: varchar(64)
      fetched_at: timestamp

# Documentation
docs-paths: ["docs"]
