stavanger_parking:
  target: dev
  outputs:
    dev:
      type: trino
      host: localhost
      port: 8080
      user: trino
      password: ""
      catalog: memory
      schema: default
      threads: 4
      http_scheme: http
      use_ssl: false
      verify: false
      session_properties:
        query_max_execution_time: 1h
        query_max_run_time: 1h
        query_max_memory: 512MB
        query_max_memory_per_node: 256MB
