-- PostgreSQL Initialization Script
-- Creates databases and users for Dagster and Hive Metastore

-- Create Dagster database and user
CREATE DATABASE dagster;
CREATE USER dagster WITH PASSWORD 'dagster123';
GRANT ALL PRIVILEGES ON DATABASE dagster TO dagster;

-- Create Hive Metastore database and user
CREATE DATABASE metastore;
CREATE USER metastore WITH PASSWORD 'metastore123';
GRANT ALL PRIVILEGES ON DATABASE metastore TO metastore;

-- Connect to metastore database and create schema
\c metastore;

-- Create Hive metastore tables (basic schema)
CREATE TABLE IF NOT EXISTS DBS (
    DB_ID BIGSERIAL PRIMARY KEY,
    DESC VARCHAR(4000),
    DB_LOCATION_URI VARCHAR(4000),
    NAME VARCHAR(128) UNIQUE NOT NULL,
    OWNER_NAME VARCHAR(128),
    OWNER_TYPE VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS TBLS (
    TBL_ID BIGSERIAL PRIMARY KEY,
    CREATE_TIME INTEGER NOT NULL,
    DB_ID BIGINT NOT NULL,
    LAST_ACCESS_TIME INTEGER NOT NULL,
    OWNER VARCHAR(767),
    RETENTION INTEGER NOT NULL,
    SD_ID BIGINT,
    TBL_NAME VARCHAR(128) NOT NULL,
    TBL_TYPE VARCHAR(128),
    VIEW_EXPANDED_TEXT TEXT,
    VIEW_ORIGINAL_TEXT TEXT,
    IS_REWRITE_ENABLED BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (DB_ID) REFERENCES DBS(DB_ID)
);

CREATE TABLE IF NOT EXISTS TABLE_PARAMS (
    TBL_ID BIGINT NOT NULL,
    PARAM_KEY VARCHAR(256) NOT NULL,
    PARAM_VALUE VARCHAR(4000),
    PRIMARY KEY (TBL_ID, PARAM_KEY),
    FOREIGN KEY (TBL_ID) REFERENCES TBLS(TBL_ID)
);

CREATE TABLE IF NOT EXISTS PARTITIONS (
    PART_ID BIGSERIAL PRIMARY KEY,
    CREATE_TIME INTEGER NOT NULL,
    LAST_ACCESS_TIME INTEGER NOT NULL,
    PART_NAME VARCHAR(767),
    SD_ID BIGINT,
    TBL_ID BIGINT NOT NULL,
    FOREIGN KEY (TBL_ID) REFERENCES TBLS(TBL_ID)
);

-- Insert default database
INSERT INTO DBS (NAME, DESC, DB_LOCATION_URI, OWNER_NAME, OWNER_TYPE) 
VALUES ('default', 'Default Hive Database', 'file:///user/hive/warehouse', 'public', 'ROLE')
ON CONFLICT (NAME) DO NOTHING;

-- Grant permissions
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO metastore;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO metastore;
GRANT ALL PRIVILEGES ON SCHEMA public TO metastore;

-- Connect back to default database
\c dagster;
