version: 2

sources:
  - name: stavanger_parking
    description: "Live parking data from Stavanger municipal API"
    schema: analytics_analytics
    tables:
      - name: raw_parking_data
        description: "Raw parking data fetched from Stavanger API"
        columns:
          - name: date
            description: "Date of parking data"
          - name: time
            description: "Time of parking data"
          - name: location
            description: "Parking location name"
          - name: latitude
            description: "Latitude coordinate"
          - name: longitude
            description: "Longitude coordinate"
          - name: available_spaces
            description: "Number of available parking spaces"
          - name: timestamp
            description: "Combined date and time timestamp"
          - name: data_source
            description: "Source of the data"
          - name: ingestion_timestamp
            description: "When the data was ingested"
          - name: pipeline_run_id
            description: "Dagster pipeline run ID"
          - name: hour
            description: "Hour of the day (derived)"
          - name: day_of_week
            description: "Day of week (derived)"
          - name: month
            description: "Month (derived)"
          - name: year
            description: "Year (derived)"
          - name: location_type
            description: "Type of parking location (derived)"
          - name: estimated_total_capacity
            description: "Estimated total parking capacity"
          - name: estimated_occupied_spaces
            description: "Estimated occupied spaces"
          - name: estimated_occupancy_rate
            description: "Estimated occupancy rate percentage"
          - name: data_quality_score
            description: "Data quality score"
