#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - git
  - curl
  - wget
  - unzip
  - htop
  - vim
  - tree
  - jq
  - python3
  - python3-pip
  - python3-venv
  - nodejs
  - npm

users:
  - name: ${admin_user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${admin_ssh_key}

runcmd:
  # Start and enable Docker
  - systemctl start docker
  - systemctl enable docker
  
  # Add admin user to docker group
  - usermod -aG docker ${admin_user}
  
  # Install Docker Compose
  - curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  
  # Create project directory
  - mkdir -p /opt/foss-dataplatform
  - chown ${admin_user}:${admin_user} /opt/foss-dataplatform
  
  # Set up swap file for better performance
  - fallocate -l 2G /swapfile
  - chmod 600 /swapfile
  - mkswap /swapfile
  - swapon /swapfile
  - echo '/swapfile none swap sw 0 0' >> /etc/fstab
  
  # Optimize system for data workloads
  - echo 'vm.swappiness=10' >> /etc/sysctl.conf
  - echo 'vm.vfs_cache_pressure=50' >> /etc/sysctl.conf
  
  # Create data directories
  - mkdir -p /data/{iceberg,delta,logs,backups}
  - chown -R ${admin_user}:${admin_user} /data
  
  # Set up log rotation
  - echo '/data/logs/*.log { daily missingok rotate 7 compress delaycompress notifempty create 644 root root }' > /etc/logrotate.d/dataplatform

final_message: "FOSS Data Platform server setup complete!"
