apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    
  # Trino datasource commented out until plugin is available
  # - name: Trino
  #   type: trino
  #   access: proxy
  #   url: http://trino-coordinator:8080
  #   editable: true
  #   jsonData:
  #     catalog: memory
  #     schema: default
  #     user: admin
