name: 'stavanger_parking'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'stavanger_parking'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Ensure required schemas exist for Medallion Architecture (Iceberg)
on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS iceberg.analytics_staging"    # Bronze & Silver Layer
  - "CREATE SCHEMA IF NOT EXISTS iceberg.analytics"            # Gold Layer (Business Layer)
  - "CREATE SCHEMA IF NOT EXISTS iceberg.analytics_audit"      # Audit & Quality Layer

# Delta load specific configurations
vars:
  pipeline_run_id: "{{ run_started_at.strftime('%Y%m%d_%H%M%S') }}"
  load_type: "delta_load"
  data_source: "stavanger_api"

# Medallion Architecture Model Configuration
models:
  stavanger_parking:

    # 🥉 BRONZE LAYER - Raw Data Landing Zone
    bronze:
      +materialized: incremental
      +incremental_strategy: merge
      +schema: analytics_staging
      +tags: ['bronze', 'landing', 'raw', 'iceberg', 'incremental']
      landing:
        +partition_by: {"field": "recorded_date", "data_type": "date"}
      audit:
        +materialized: incremental
        +incremental_strategy: append
        +tags: ['bronze', 'audit', 'data_quality', 'monitoring']

    # 🥈 SILVER LAYER - Cleaned & Enriched Data
    silver:
      +schema: analytics_staging
      +tags: ['silver', 'clean', 'enriched', 'validated']
      entities:
        +materialized: incremental
        +incremental_strategy: merge
        +tags: ['silver', 'entities', 'dimension', 'master_data']
      facts:
        +materialized: incremental
        +incremental_strategy: merge
        +partition_by: {"field": "recorded_date", "data_type": "date"}
        +tags: ['silver', 'facts', 'measures', 'incremental']
      conformed:
        +materialized: table
        +tags: ['silver', 'conformed', 'dimension', 'shared']

    # 🥇 GOLD LAYER - Business Ready Analytics
    gold:
      +schema: analytics
      +tags: ['gold', 'business', 'analytics', 'reporting']
      reports:
        +materialized: table
        +tags: ['gold', 'reports', 'business_intelligence', 'kpi']
      dashboards:
        +materialized: view
        +tags: ['gold', 'dashboards', 'real_time', 'metrics']
      analytics:
        +materialized: table
        +tags: ['gold', 'analytics', 'predictive', 'ml_features']

    # Legacy configurations (to be deprecated)
    staging:
      +materialized: incremental
      +incremental_strategy: merge
      +schema: analytics_staging
      +tags: ['legacy', 'staging', 'deprecated']
    intermediate:
      +materialized: table
      +schema: analytics_staging
      +tags: ['legacy', 'intermediate', 'deprecated']
    marts:
      +materialized: table
      +schema: analytics
      +tags: ['legacy', 'marts', 'deprecated']

# Seeds configuration
seeds:
  stavanger_parking:
    +schema: analytics
    +column_types:
      name: varchar(255)
      available_spaces: integer
      lat: varchar(64)
      lon: varchar(64)
      fetched_at: varchar(64)  # Store as varchar first, then cast to timestamp

# Documentation
docs-paths: ["docs"]
