name: 'stavanger_parking'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'stavanger_parking'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Ensure required schemas exist (Iceberg)
on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS iceberg.analytics"
  - "CREATE SCHEMA IF NOT EXISTS iceberg.analytics_staging"
  - "CREATE SCHEMA IF NOT EXISTS iceberg.analytics_intermediate"

# Configuring data models
models:
  stavanger_parking:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: table
      +schema: analytics_staging
    intermediate:
      +materialized: table
      +schema: analytics_intermediate
    marts:
      +materialized: table
      +schema: analytics
    core:
      +materialized: table
      +schema: analytics
    marketing:
      +materialized: table
      +schema: analytics

# Seeds configuration
seeds:
  stavanger_parking:
    +schema: analytics
    +column_types:
      name: varchar(255)
      available_spaces: integer
      lat: varchar(64)
      lon: varchar(64)
      fetched_at: varchar(64)  # Store as varchar first, then cast to timestamp

# Documentation
docs-paths: ["docs"]
